### ISSUE TITLE
[question]关于useBuiltIns的entry

### ISSUE THREAD

**Issue by Omelettesheep** [jruit/webpack-babel#1]
babel10-9的例子中，我尝试去掉了babel/polyfill，把browserslist换成了一个较低的版本，发现entry的配置下，转出来的b.js和用usage转出来好像是一样的。甚至我改成了false，也还是一样的输出，想问下我是有哪边配置错了吗
```
//package
{
  "name": "babel10-8",
  "version": "1.0.0",
  "description": "https://www.jiangruitao.com",
  "main": "index.js",
  "scripts": {
    "dev": "babel a.js -o b.js"
  },
  "keywords": [
    "webpack",
    "babel",
    "tutorial"
  ],
  "author": "jruit",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "7.13.10",
    "@babel/core": "7.13.10",
    "@babel/preset-env": "7.13.10"
  },
  "browserslist": [
    "chrome 5"
  ],
  "dependencies": {
    "@babel/polyfill": "7.12.1"
  }
}
`

`
// babel.config
module.exports = {
  presets: [["@babel/env", {
    useBuiltIns: false
  }]],
  plugins: []
}
`

`a.js
// import '@babel/polyfill';

var promise = Promise.resolve('ok');
console.log(promise);

class Person {
    sayname() {
      return 'name'
    }
  }
  
  var john = new Person()
  const a = [1,2,3]
  console.log(john, a.flat())
`

`
// 转义出来的b.js
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }

// import '@babel/polyfill';
var promise = Promise.resolve('ok');
console.log(promise);

var Person = /*#__PURE__*/function () {
  function Person() {
    _classCallCheck(this, Person);
  }

  _createClass(Person, [{
    key: "sayname",
    value: function sayname() {
      return 'name';
    }
  }]);

  return Person;
}();

var john = new Person();
var a = [1, 2, 3];
console.log(john, a.flat());

`

**Comment by jruit** [comment]
> babel10-9的例子中，我尝试去掉了babel/polyfill，把browserslist换成了一个较低的版本，发现entry的配置下，转出来的b.js和用usage转出来好像是一样的。甚至我改成了false，也还是一样的输出，想问下我是有哪边配置错了吗
> 
> ```
> //package
> {
>   "name": "babel10-8",
>   "version": "1.0.0",
>   "description": "https://www.jiangruitao.com",
>   "main": "index.js",
>   "scripts": {
>     "dev": "babel a.js -o b.js"
>   },
>   "keywords": [
>     "webpack",
>     "babel",
>     "tutorial"
>   ],
>   "author": "jruit",
>   "license": "ISC",
>   "devDependencies": {
>     "@babel/cli": "7.13.10",
>     "@babel/core": "7.13.10",
>     "@babel/preset-env": "7.13.10"
>   },
>   "browserslist": [
>     "chrome 5"
>   ],
>   "dependencies": {
>     "@babel/polyfill": "7.12.1"
>   }
> }
> `
> 
> `
> // babel.config
> module.exports = {
>   presets: [["@babel/env", {
>     useBuiltIns: false
>   }]],
>   plugins: []
> }
> `
> 
> `a.js
> // import '@babel/polyfill';
> 
> var promise = Promise.resolve('ok');
> console.log(promise);
> 
> class Person {
>     sayname() {
>       return 'name'
>     }
>   }
>   
>   var john = new Person()
>   const a = [1,2,3]
>   console.log(john, a.flat())
> `
> 
> `
> // 转义出来的b.js
> "use strict";
> 
> function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
> 
> function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }
> 
> function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); Object.defineProperty(Constructor, "prototype", { writable: false }); return Constructor; }
> 
> // import '@babel/polyfill';
> var promise = Promise.resolve('ok');
> console.log(promise);
> 
> var Person = /*#__PURE__*/function () {
>   function Person() {
>     _classCallCheck(this, Person);
>   }
> 
>   _createClass(Person, [{
>     key: "sayname",
>     value: function sayname() {
>       return 'name';
>     }
>   }]);
> 
>   return Person;
> }();
> 
> var john = new Person();
> var a = [1, 2, 3];
> console.log(john, a.flat());
> 
> `
> ```
你好，没有看明白，请做一下详细的配置对比

**Comment by Omelettesheep** [comment]
sorry我看错了。。promise应该是preset里就能直接转的，我这边跟垫片搞混了。
