### ISSUE TITLE
建议-《webpack+babel入门与实例详解》第二章第四节contenthash没有说清楚与contenthash的区别

### ISSUE THREAD

**Issue by haishangfeie** [jruit/webpack-babel#2]
你好，关于《webpack+babel入门与实例详解》，想提个建议：
第二章第四节，关于contenthash的讲解感觉有点模糊，只提到了CSS时一般使用contenthash，没有说清楚chunkhash和contnethash的区别。如果书籍以后有机会再版的话，也许可以考虑补充一下。
![image](https://user-images.githubusercontent.com/26127631/230067678-611ad949-3128-4dad-9838-1f513933cecb.png)

**Comment by jruit** [comment]
感谢建议
