### ISSUE TITLE
[示例webpack5-2]示例运行报错

### ISSUE THREAD

**Issue by haishangfeie** [jruit/webpack-babel#3]
安装示例依赖，运行`npx webpack serve` 发现无法运行，报错

```bash
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\@webpack-cli\serve\lib\index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\webpack-cli\lib\webpack-cli.js:1687:7)
```

经排查，是`webpack-cli` 版本过低导致的，需要调整版本：`"webpack-cli": "4.10.0"`

因为书籍提到过，示例可能会有版本低导致的报错，所以可能这个是作者有预料的问题？不管怎样，看到了就报告一下。

**Comment by jruit** [comment]
写本书时预料到未来会出现该问题，所以书中加了提示。一方面希望读者尽量使用书中版本一致的Node等工具，另一方面npm依赖的依赖未来可能会有变动。

感谢反馈

> 安装示例依赖，运行`npx webpack serve` 发现无法运行，报错
> 
> ```shell
> [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
>     at Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\@webpack-cli\serve\lib\index.js:146:35)
>     at async Promise.all (index 1)
>     at async Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\webpack-cli\lib\webpack-cli.js:1687:7)
> ```
> 
> 经排查，是`webpack-cli` 版本过低导致的，需要调整版本：`"webpack-cli": "4.10.0"`
> 
> 因为书籍提到过，示例可能会有版本低导致的报错，所以可能这个是作者有预料的问题？不管怎样，看到了就报告一下。

写本书时预料到未来会出现该问题，所以书中加了提示。一方面希望读者尽量使用书中版本一致的Node等工具，另一方面npm依赖的依赖未来可能会有变动。

感谢反馈

**Comment by jruit** [comment]
> 安装示例依赖，运行`npx webpack serve` 发现无法运行，报错
> 
> ```shell
> [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
>     at Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\@webpack-cli\serve\lib\index.js:146:35)
>     at async Promise.all (index 1)
>     at async Command.<anonymous> (E:\code\book-learn\webpack-babel-rumenyushlixiangjie\5\webpack5-2\node_modules\webpack-cli\lib\webpack-cli.js:1687:7)
> ```
> 
> 经排查，是`webpack-cli` 版本过低导致的，需要调整版本：`"webpack-cli": "4.10.0"`
> 
> 因为书籍提到过，示例可能会有版本低导致的报错，所以可能这个是作者有预料的问题？不管怎样，看到了就报告一下。

写本书时预料到未来会出现该问题，所以书中加了提示。一方面希望读者尽量使用书中版本一致的Node等工具，另一方面npm依赖的依赖未来可能会有变动。

感谢反馈
